-- SQL Seed Script for 50 Random/Realistic Tickets
-- Database: db_layanan_ti

USE db_layanan_ti;

-- Clear comments and tickets to start fresh if desired (optional, commented out)
-- DELETE FROM comments;
-- DELETE FROM tickets WHERE id != 'TKT-2026-001' AND id != 'TKT-2026-002';

INSERT IGNORE INTO tickets (id, pengirimId, pengirimName, jenis, layananKategori, layananSub, layanan, detail, tanggal, tanggalUpdate, kasubbagId, kasubbagName, solverId, solverName, status, alasanTolak, catatanKasubbag) VALUES
-- Subbag Infrastruktur (k1 - Ir. Hartono, M.T.)
('TKT-2026-003', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Teknologi', 'Layanan Intranet', 'Penyediaan kabel LAN', 'Kabel LAN di meja kerja saya putus karena terjepit laci meja. Mohon penggantian agar bisa online kembali.', '2026-06-25', '2026-06-25 10:30', 'k1', 'Ir. Hartono, M.T.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-004', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Teknologi', 'Layanan Intranet', 'Penyediaan kabel LAN', 'Kabel LAN di ruang rapat lantai 2 tidak terhubung. Sudah dicoba ganti port tapi tetap no internet access.', '2026-06-25', '2026-06-25 14:22', 'k1', 'Ir. Hartono, M.T.', 's1_1', 'Supriyadi (Infra Solver 1)', 'Dikerjakan', NULL, NULL),
('TKT-2026-005', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Teknologi', 'Layanan Internet', 'Penyediaan akses internet', 'Akses WiFi BPK-Guest sangat lambat hari ini di sayap timur lantai 3. Gagal memuat halaman portal.', '2026-06-26', '2026-06-26 09:05', 'k1', 'Ir. Hartono, M.T.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-006', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Teknologi', 'Layanan Internet', 'Penyediaan akses internet', 'Request pembukaan port khusus untuk akses pengiriman file audit besar ke instansi luar (FTP).', '2026-06-26', '2026-06-27 16:30', 'k1', 'Ir. Hartono, M.T.', 's1_2', 'Aris Nugroho (Infra Solver 2)', 'Selesai', NULL, 'Port FTP eksternal telah dibuka secara aman dan dibatasi hanya untuk alamat IP tujuan resmi.'),
('TKT-2026-007', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Teknologi', 'Layanan Internet', 'Penyediaan akses internet', 'Koneksi internet di ruangan kami sering terputus setiap 15 menit sekali. Mohon dicek switch hub lokal.', '2026-06-27', '2026-06-27 11:45', 'k1', 'Ir. Hartono, M.T.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-008', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Teknologi', 'Layanan Intranet', 'Penyediaan kabel LAN', 'Permintaan kabel LAN sepanjang 10 meter untuk kebutuhan presentasi di Aula Utama minggu depan.', '2026-06-27', '2026-06-28 10:10', 'k1', 'Ir. Hartono, M.T.', 's1_3', 'Dimas Saputra (Infra Solver 3)', 'Selesai', NULL, 'Kabel LAN 10 meter telah disiapkan dan diserahkan kepada panitia di Aula.'),
('TKT-2026-009', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Teknologi', 'Layanan Internet', 'Penyediaan akses internet', 'Koneksi LAN lemot total di ruangan saya. Speed test hanya terbaca 1 Mbps. Sangat mengganggu input e-audit.', '2026-06-28', '2026-06-28 14:50', 'k1', 'Ir. Hartono, M.T.', 's1_1', 'Supriyadi (Infra Solver 1)', 'Kembalikan tiket ke operator', 'Tolong diperiksa kembali kategori layanannya. Masalah internet lambat ini harusnya dikonfirmasi ke subbag MIOT/router.', NULL),
('TKT-2026-010', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Teknologi', 'Layanan Intranet', 'Penyediaan akses internet', 'Switch hub di ruangan kami mati total, lampu indikator power tidak menyala. Seluruh staff terputus.', '2026-06-29', '2026-06-29 08:30', 'k1', 'Ir. Hartono, M.T.', 's1_2', 'Aris Nugroho (Infra Solver 2)', 'Dikerjakan', NULL, NULL),

-- Subbag Pelayanan TIK (k2 - Dra. Wulandari, M.Si.)
('TKT-2026-011', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Dukungan TIK', 'Layanan Akun', 'Pembuatan/Perubahan Akun', 'Lupa password akun Windows AD. Mohon di-reset karena saya tidak bisa login ke PC kantor.', '2026-06-29', '2026-06-29 09:12', 'k2', 'Dra. Wulandari, M.Si.', 's2_1', 'Farah Amalia (TIK Solver 1)', 'Selesai', NULL, 'Password akun Active Directory telah direset. Silakan login kembali dengan password sementara BpkRi2026.'),
('TKT-2026-012', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Dukungan TIK', 'Layanan Akun', 'Pembuatan/Perubahan Akun', 'Permintaan pembuatan email dinas BPK baru untuk staff magang di subbagian kami.', '2026-06-29', '2026-06-29 11:40', 'k2', 'Dra. Wulandari, M.Si.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-013', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Dukungan TIK', 'Layanan Perangkat', 'Peminjaman Perangkat TIK', 'Memohon peminjaman 2 unit laptop dinas untuk dinas luar kota tim pemeriksa selama 14 hari.', '2026-06-30', '2026-06-30 08:15', 'k2', 'Dra. Wulandari, M.Si.', 's2_2', 'Bayu Anggara (TIK Solver 2)', 'Ditugaskan', NULL, NULL),
('TKT-2026-014', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Dukungan TIK', 'Layanan Perangkat', 'Pemeliharaan Perangkat TIK', 'Komputer AIO saya sering mati mendadak sendiri. Bunyi kipas di dalam CPU sangat bising dan panas.', '2026-06-30', '2026-06-30 10:50', 'k2', 'Dra. Wulandari, M.Si.', 's2_3', 'Sonia Fitri (TIK Solver 3)', 'Dikerjakan', NULL, NULL),
('TKT-2026-015', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Dukungan TIK', 'Layanan Akun', 'Pembuatan/Perubahan Akun', 'Reset password Portal BPK Mandiri. Token OTP tidak masuk ke nomor handphone saya.', '2026-06-30', '2026-06-30 15:45', 'k2', 'Dra. Wulandari, M.Si.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-016', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Dukungan TIK', 'Layanan Perangkat', 'Peminjaman Perangkat TIK', 'Permintaan sewa LCD Proyektor untuk rapat koordinasi nasional di ruang VIP besok pagi.', '2026-07-01', '2026-07-01 07:45', 'k2', 'Dra. Wulandari, M.Si.', 's2_1', 'Farah Amalia (TIK Solver 1)', 'Selesai', NULL, 'LCD Proyektor beserta kabel HDMI dan pointer telah dipasang dan ditest di ruang VIP.'),
('TKT-2026-017', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Dukungan TIK', 'Layanan Perangkat', 'Pemeliharaan Perangkat TIK', 'Printer Epson L3110 di meja kerja saya macet/paper jam, kertas tersangkut di dalam roller roller penarik.', '2026-07-01', '2026-07-01 09:00', 'k2', 'Dra. Wulandari, M.Si.', NULL, NULL, 'Pending', NULL, NULL),

-- Subbag SIM-P (k3 - Rizal Pratama, S.T.)
('TKT-2026-018', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Pemeriksaan', 'Layanan Aplikasi SIAP', 'Aplikasi SIAP', 'Gagal login ke aplikasi SIAP BPK, muncul error invalid credential padahal password AD sudah benar.', '2026-06-25', '2026-06-25 11:20', 'k3', 'Rizal Pratama, S.T.', 's3_1', 'Deni Ardiansyah (SIM-P Solver 1)', 'Selesai', NULL, 'Akun user telah disinkronisasikan ulang dengan database Active Directory pusat BPK.'),
('TKT-2026-019', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Pemeriksaan', 'Layanan Aplikasi SIAP', 'Aplikasi SIAP', 'Aplikasi e-Kertas Kerja Audit (e-KKA) macet saat proses upload lampiran bukti Excel berukuran 40MB.', '2026-06-26', '2026-06-26 14:15', 'k3', 'Rizal Pratama, S.T.', 's3_2', 'Eko Prasetyo (SIM-P Solver 2)', 'Dikerjakan', NULL, NULL),
('TKT-2026-020', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Pemeriksaan', 'Layanan Aplikasi SIAP', 'Aplikasi SIAP', 'Permintaan penambahan hak akses modul Supervisor Pemeriksa untuk akun Pak Kepala Sub Auditorat.', '2026-06-27', '2026-06-27 10:00', 'k3', 'Rizal Pratama, S.T.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-021', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Pemeriksaan', 'Layanan Aplikasi SIAP', 'Aplikasi SIAP', 'Data Tim Pemeriksa untuk entitas Pemprov Jateng Semester I tidak muncul di dashboard alokasi tugas.', '2026-06-28', '2026-06-28 13:40', 'k3', 'Rizal Pratama, S.T.', 's3_3', 'Lilis Handayani (SIM-P Solver 3)', 'Ditugaskan', NULL, NULL),
('TKT-2026-022', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Pemeriksaan', 'Layanan Aplikasi SIAP', 'Aplikasi SIAP', 'Laporan LHP format PDF tidak bisa digenerate dari aplikasi. Proses loading terus sampai timeout.', '2026-06-29', '2026-06-29 16:10', 'k3', 'Rizal Pratama, S.T.', 's3_1', 'Deni Ardiansyah (SIM-P Solver 1)', 'Selesai', NULL, 'Bug memory leak pada engine PDF renderer telah diperbaiki di server staging, laporan berhasil dicetak.'),

-- Subbag SIM-K (k4 - Hendra Gunawan, S.Kom.)
('TKT-2026-023', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Kelembagaan', 'Layanan Aplikasi Kepegawaian', 'Aplikasi Kepegawaian (SISDM)', 'Nama dan pangkat saya belum ter-update setelah kenaikan pangkat periode April 2026 di portal SISDM.', '2026-06-25', '2026-06-25 15:30', 'k4', 'Hendra Gunawan, S.Kom.', 's4_1', 'Wawan Hermawan (SIM-K Solver 1)', 'Selesai', NULL, 'Pangkat telah disesuaikan secara manual berdasarkan surat keputusan penyesuaian pangkat golongan BPK.'),
('TKT-2026-024', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Kelembagaan', 'Layanan Aplikasi Kepegawaian', 'Aplikasi Kepegawaian (SISDM)', 'Reset password akun SISDM. Link reset yang dikirim ke email dinas kadaluarsa terlalu cepat.', '2026-06-26', '2026-06-26 11:15', 'k4', 'Hendra Gunawan, S.Kom.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-025', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Kelembagaan', 'Layanan Aplikasi Presensi', 'Aplikasi Kepegawaian (SISDM)', 'Aplikasi Presensi e-Movit BPK sering eror fake GPS padahal saya sudah di dalam area kantor WFO.', '2026-06-27', '2026-06-27 08:45', 'k4', 'Hendra Gunawan, S.Kom.', 's4_2', 'Fitriani (SIM-K Solver 2)', 'Dikerjakan', NULL, NULL),
('TKT-2026-026', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Kelembagaan', 'Layanan Aplikasi Presensi', 'Aplikasi Kepegawaian (SISDM)', 'Presensi kehadiran lembur hari Sabtu kemarin tidak tercatat di rekapitulasi bulanan e-Movit.', '2026-06-28', '2026-06-28 14:02', 'k4', 'Hendra Gunawan, S.Kom.', 's4_3', 'Aditya Pratama (SIM-K Solver 3)', 'Ditugaskan', NULL, NULL),
('TKT-2026-027', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Kelembagaan', 'Layanan Aplikasi Kepegawaian', 'Aplikasi Kepegawaian (SISDM)', 'Menu pengisian SKP Tahunan 2026 terkunci/tidak bisa diedit padahal batas akhir pengisian belum lewat.', '2026-06-29', '2026-06-29 10:20', 'k4', 'Hendra Gunawan, S.Kom.', 's4_1', 'Wawan Hermawan (SIM-K Solver 1)', 'Kembalikan tiket ke operator', 'Pengaduan ini ditolak karena masa pengisian SKP di sistem telah ditutup berdasarkan edaran Biro SDM.', NULL),

-- Subbag Sains Data (k5 - Dr. Nuraini, M.Sc.)
('TKT-2026-028', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Data', 'Layanan Penyediaan Data Analisis', 'Penyediaan dataset audit', 'Memohon dataset anggaran Pemda se-Provinsi Riau Tahun Anggaran 2025 untuk kebutuhan komparasi audit.', '2026-06-25', '2026-06-25 13:00', 'k5', 'Dr. Nuraini, M.Sc.', 's5_1', 'Rian Setiawan (Sains Solver 1)', 'Selesai', NULL, 'Dataset anggaran Pemda Riau 2025 format CSV telah diekspor dan diunggah ke cloud folder khusus tim auditor.'),
('TKT-2026-029', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Data', 'Layanan Penyediaan Data Analisis', 'Penyediaan dataset audit', 'Gagal memuat visualisasi tren fraud di dashboard Tableau Analytics BPK. Muncul error database connection.', '2026-06-26', '2026-06-26 16:50', 'k5', 'Dr. Nuraini, M.Sc.', 's5_2', 'Kartika Sari (Sains Solver 2)', 'Dikerjakan', NULL, NULL),
('TKT-2026-030', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Data', 'Layanan Penyediaan Data Analisis', 'Penyediaan dataset audit', 'Mohon diberikan akses ke klaster Hadoop Big Data BPK untuk ekstraksi logs transaksi keuangan pemda.', '2026-06-27', '2026-06-27 10:30', 'k5', 'Dr. Nuraini, M.Sc.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-031', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Data', 'Layanan Penyediaan Data Analisis', 'Penyediaan dataset audit', 'Proses query data analytics pembanding harga barang e-katalog LKPP timeout setelah berjalan 5 menit.', '2026-06-28', '2026-06-28 11:20', 'k5', 'Dr. Nuraini, M.Sc.', 's5_3', 'Andi Wijaya (Sains Solver 3)', 'Ditugaskan', NULL, NULL),
('TKT-2026-032', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Data', 'Layanan Penyediaan Data Analisis', 'Penyediaan dataset audit', 'Dataset rincian data bansos Kementerian Sosial 2025 tidak bisa diunduh oleh akun saya. Izin akses ditolak.', '2026-06-29', '2026-06-29 14:40', 'k5', 'Dr. Nuraini, M.Sc.', 's5_1', 'Rian Setiawan (Sains Solver 1)', 'Selesai', NULL, 'Akses role audit tim Anda telah diperbarui untuk membaca skema tabel bantuan sosial.'),

-- Subbag Tata Kelola TI (k6 - Bambang Susilo, S.Kom.)
('TKT-2026-033', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Tata Kelola TI', 'Layanan Keamanan Informasi', 'Penyusunan standar TI', 'Permintaan salinan dokumen resmi Kebijakan Keamanan Informasi BPK versi terbaru untuk kelengkapan audit IT.', '2026-06-25', '2026-06-25 14:15', 'k6', 'Bambang Susilo, S.Kom.', 's6_1', 'Heri Susanto (Tata Kelola Solver 1)', 'Selesai', NULL, 'Dokumen PDF standar kebijakan keamanan informasi ISO 27001 BPK telah dikirim ke email dinas pemohon.'),
('TKT-2026-034', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Tata Kelola TI', 'Layanan Keamanan Informasi', 'Penyusunan standar TI', 'Apakah ada template formulir persetujuan pemanfaatan open-source software untuk internal BPK?', '2026-06-26', '2026-06-26 10:10', 'k6', 'Bambang Susilo, S.Kom.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-035', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Tata Kelola TI', 'Layanan Keamanan Informasi', 'Penyusunan standar TI', 'Permintaan review kelayakan arsitektur IT untuk sistem monitoring terpusat yang diajukan pihak ketiga.', '2026-06-27', '2026-06-27 15:40', 'k6', 'Bambang Susilo, S.Kom.', 's6_2', 'Melinda Putri (Tata Kelola Solver 2)', 'Dikerjakan', NULL, NULL),

-- Subbag Keamanan TI (k7 - Rina Marliani, M.M.)
('TKT-2026-036', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Keamanan TI', 'Layanan Akses VPN', 'Akses VPN BPK', 'Mohon bantuan konfigurasi VPN FortiClient di laptop dinas saya. Selalu membalas error TLS handshake.', '2026-06-25', '2026-06-25 16:05', 'k7', 'Rina Marliani, M.M.', 's7_1', 'Angga Saputra (Sec Solver 1)', 'Selesai', NULL, 'Sertifikat enkripsi VPN terbaru telah diexport and di-import ulang ke laptop pemohon.'),
('TKT-2026-037', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Keamanan TI', 'Layanan Akses VPN', 'Akses VPN BPK', 'Permintaan perpanjangan masa berlaku akun VPN BPK RI karena tim kami masih audit luar daerah s.d Juli.', '2026-06-26', '2026-06-26 09:20', 'k7', 'Rina Marliani, M.M.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-038', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Keamanan TI', 'Layanan Penanganan Insiden Keamanan', 'Antivirus & Firewall', 'Ada pop-up Windows Defender mendeteksi virus Trojan di folder download saya. Mohon bantuan scanning mendalam.', '2026-06-27', '2026-06-27 11:30', 'k7', 'Rina Marliani, M.M.', 's7_2', 'Diana Lestari (Sec Solver 2)', 'Dikerjakan', NULL, NULL),
('TKT-2026-039', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Keamanan TI', 'Layanan Penanganan Insiden Keamanan', 'Antivirus & Firewall', 'Akun e-audit saya terblokir IP Address karena salah memasukkan password sebanyak 5 kali berturut-turut.', '2026-06-28', '2026-06-28 14:15', 'k7', 'Rina Marliani, M.M.', 's7_3', 'Rudi Hartono (Sec Solver 3)', 'Ditugaskan', NULL, NULL),
('TKT-2026-040', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Keamanan TI', 'Layanan Akses VPN', 'Akses VPN BPK', 'Akses internet laptop saya putus total saat aplikasi VPN FortiClient dinyalakan. Split tunneling eror.', '2026-06-29', '2026-06-29 09:45', 'k7', 'Rina Marliani, M.M.', 's7_1', 'Angga Saputra (Sec Solver 1)', 'Selesai', NULL, 'Konfigurasi route metrics pada VPN client disesuaikan sehingga koneksi internet non-BPK tetap aktif.'),

-- Subbag MIOT (k8 - Teguh Prasetyo, S.T.)
('TKT-2026-041', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Infrastruktur Dan Keamanan TIK', 'Layanan Monitoring Suhu Server', 'Sensor Suhu Ruang Server', 'Sensor suhu di Rak 4 Server Center berkedip merah dan menunjukkan suhu 26 derajat (ambang batas overheat).', '2026-06-25', '2026-06-25 15:40', 'k8', 'Teguh Prasetyo, S.T.', 's8_1', 'Fajar Ramadan (MIOT Solver 1)', 'Selesai', NULL, 'AC presisi cadangan telah dinyalakan secara otomatis untuk mendinginkan rak server kembali ke 19 derajat.'),
('TKT-2026-042', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Infrastruktur Dan Keamanan TIK', 'Layanan Monitoring Suhu Server', 'Sensor Suhu Ruang Server', 'Dashboard monitoring IOT suhu ruang server tidak menampilkan grafik historis mingguan. Grafik kosong.', '2026-06-26', '2026-06-26 10:22', 'k8', 'Teguh Prasetyo, S.T.', 's8_2', 'Indah Permata (MIOT Solver 2)', 'Dikerjakan', NULL, NULL),
('TKT-2026-043', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Infrastruktur Dan Keamanan TIK', 'Layanan Monitoring Suhu Server', 'Sensor Suhu Ruang Server', 'Alarm buzzer di ruang UPS berbunyi terus menerus, terdeteksi fluktuasi input tegangan listrik PLN.', '2026-06-27', '2026-06-27 16:50', 'k8', 'Teguh Prasetyo, S.T.', NULL, NULL, 'Pending', NULL, NULL),

-- Additional general mixed tickets
('TKT-2026-044', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Teknologi', 'Layanan Internet', 'Penyediaan akses internet', 'Request WiFi account khusus VIP tamu BPK RI dari Kementerian BUMN untuk rapat esok hari.', '2026-06-28', '2026-06-28 09:12', 'k1', 'Ir. Hartono, M.T.', 's1_1', 'Supriyadi (Infra Solver 1)', 'Selesai', NULL, 'Akun WiFi tamu dengan durasi 24 jam telah dibuat dan kredensial diserahkan kepada protokoler.'),
('TKT-2026-045', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Dukungan TIK', 'Layanan Perangkat', 'Peminjaman Perangkat TIK', 'Permintaan scanner portable untuk proses pemindaian dokumen kertas kuesioner audit di lapangan.', '2026-06-28', '2026-06-28 11:35', 'k2', 'Dra. Wulandari, M.Si.', 's2_2', 'Bayu Anggara (TIK Solver 2)', 'Ditugaskan', NULL, NULL),
('TKT-2026-046', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Pemeriksaan', 'Layanan Aplikasi SIAP', 'Aplikasi SIAP', 'Fitur filter berdasarkan tahun pemeriksaan tidak bekerja di halaman pencarian database SIAP.', '2026-06-29', '2026-06-29 14:10', 'k3', 'Rizal Pratama, S.T.', 's3_2', 'Eko Prasetyo (SIM-P Solver 2)', 'Dikerjakan', NULL, NULL),
('TKT-2026-047', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Kelembagaan', 'Layanan Aplikasi Presensi', 'Aplikasi Kepegawaian (SISDM)', 'Gagal sinkron data presensi wajah menggunakan tablet di lobby depan BPK. Kamera tidak mendeteksi wajah.', '2026-06-29', '2026-06-29 16:45', 'k4', 'Hendra Gunawan, S.Kom.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-048', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Data', 'Layanan Penyediaan Data Analisis', 'Penyediaan dataset audit', 'Gagal memuat dataset audit eksternal format XML dari BPKP. Parser e-Audit membalas corrupt tag.', '2026-06-30', '2026-06-30 10:20', 'k5', 'Dr. Nuraini, M.Sc.', 's5_1', 'Rian Setiawan (Sains Solver 1)', 'Selesai', NULL, 'File XML BPKP memiliki kesalahan format tag penutup. Telah dibersihkan menggunakan Python script dan di-import ulang.'),
('TKT-2026-049', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Tata Kelola TI', 'Layanan Keamanan Informasi', 'Penyusunan standar TI', 'Permintaan standar konfigurasi minimal (hardening guide) untuk Linux Server di lingkungan BPK.', '2026-06-30', '2026-06-30 15:10', 'k6', 'Bambang Susilo, S.Kom.', 's6_1', 'Heri Susanto (Tata Kelola Solver 1)', 'Dikerjakan', NULL, NULL),
('TKT-2026-050', 'u1', 'Budi Santoso', 'Permintaan', 'Layanan Keamanan TI', 'Layanan Akses VPN', 'Akses VPN BPK', 'VPN FortiClient sering DC sendiri setiap 5 menit ketika sedang remote SQL server. Sangat tidak stabil.', '2026-06-30', '2026-07-01 09:05', 'k7', 'Rina Marliani, M.M.', 's7_2', 'Diana Lestari (Sec Solver 2)', 'Selesai', NULL, 'Keep-alive interval pada Gateway VPN Firewall BPK telah disesuaikan menjadi 60 detik.'),
('TKT-2026-051', 'u2', 'Siti Rahayu', 'Permintaan', 'Layanan Infrastruktur Dan Keamanan TIK', 'Layanan Monitoring Suhu Server', 'Sensor Suhu Ruang Server', 'Apakah sensor monitoring kelembapan udara (humidity) di ruang data center lantai 2 terintegrasi ke IoT?', '2026-07-01', '2026-07-01 10:30', 'k8', 'Teguh Prasetyo, S.T.', NULL, NULL, 'Pending', NULL, NULL),
('TKT-2026-052', 'u3', 'Ahmad Fauzi', 'Permintaan', 'Layanan Dukungan TIK', 'Layanan Akun', 'Pembuatan/Perubahan Akun', 'Permintaan reset password akun email dinas. Password lama terindikasi bocor karena menerima spam.', '2026-07-01', '2026-07-01 11:45', 'k2', 'Dra. Wulandari, M.Si.', 's2_1', 'Farah Amalia (TIK Solver 1)', 'Selesai', NULL, 'Password telah di-reset dan paksaan perubahan password saat login pertama (must change password) telah diaktifkan.'),
('TKT-2026-053', 'u4', 'Dewi Kusuma', 'Permintaan', 'Layanan Aplikasi Sistem Informasi Pemeriksaan', 'Layanan Aplikasi SIAP', 'Aplikasi SIAP', 'Request modul backup otomatis database lokal e-Audit BPK ke storage USB eksternal tim pemeriksa.', '2026-07-01', '2026-07-01 14:00', 'k3', 'Rizal Pratama, S.T.', NULL, NULL, 'Pending', NULL, NULL);
